/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.4-dev at Tue May 26 15:01:11 2015. */

#ifndef PB_MICROBLU_PB_H_INCLUDED
#define PB_MICROBLU_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _MicrobluState {
    pb_callback_t pin;
} MicrobluState;

typedef struct _Pin {
    uint32_t pinNumber;
    uint32_t value;
} Pin;

/* Default values for struct fields */

/* Initializer values for message structs */
#define MicrobluState_init_default               {{{NULL}, NULL}}
#define Pin_init_default                         {0, 0}
#define MicrobluState_init_zero                  {{{NULL}, NULL}}
#define Pin_init_zero                            {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define MicrobluState_pin_tag                    1
#define Pin_pinNumber_tag                        1
#define Pin_value_tag                            2

/* Struct field encoding specification for nanopb */
extern const pb_field_t MicrobluState_fields[2];
extern const pb_field_t Pin_fields[3];

/* Maximum encoded size of messages (where known) */
#define Pin_size                                 12

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MICROBLU_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
